"""update payment model

Revision ID: f300a4e94706
Revises: d7d9cbbcfeeb
Create Date: 2026-06-13 13:21:37.449737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f300a4e94706'
down_revision: Union[str, Sequence[str], None] = 'd7d9cbbcfeeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_method', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('card_last_four', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'card_last_four')
    op.drop_column('payments', 'payment_method')
    # ### end Alembic commands ###
